# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      test-output: ${{steps.Test.outputs.test }}
      coverage-output: ${{steps.Coverage.outputs.test}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: false

    - name: Build
      run: go build -o bin/ -v ./...

    - name: Test
      run: go test -v ./... -json > report.json
#      run: go test -v ./... -json > "$GITHUB_OUTPUT"

    - name: Coverage
      run: go test -coverprofile=cover.out ./hello-world/
#      run: go test -coverprofile ./hello-world/ > "$GITHUB_OUTPUT"

  sonarcloud:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        TEST_REPORT: ${{needs.build.outputs.test-output}}
        COVERAGE_REPORT: ${{needs.build.outputs.coverage-output}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
