# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: false

    - name: Build
      run: go build -o bin/ -v ./...

    - name: Test
      id: Test
      run: go test -v ./... -json > report.json

    - name: Coverage
      id: Coverage
      run: go test -coverprofile=cover.out ./hello-world/

  sonarcloud:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: false
    - run: go test -covermode=atomic -coverprofile=cover.out ./hello-world

    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: false
    - run: go test -v ./... -json > report.json

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#EOF
